version: "3"

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - kaifriends:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${KAIFRIENDS_DB_PASSWORD}
      TZ: Asia/Seoul
    restart: on-failure:5
volumes:
  kaifriends: