# Generated by Django 4.0.2 on 2022-03-25 02:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_en', models.CharField(default='', max_length=64)),
                ('degree_ko', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_en', models.CharField(default='', max_length=64)),
                ('dorm_ko', models.CharField(default='', max_length=64)),
                ('boy', models.BooleanField(default=False)),
                ('girl', models.BooleanField(default=False)),
                ('undergraduate', models.BooleanField(default=False)),
                ('graduate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='user_profiles/pictures', verbose_name='프로필')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(default=None, verbose_name='성별')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='나이')),
                ('introduction', models.CharField(blank=True, default='', max_length=256, verbose_name='자기소개')),
                ('kakao_url', models.CharField(blank=True, default='', max_length=256, verbose_name='카카오 오픈채팅 링크')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='FriendDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시간')),
                ('finalized_at', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), verbose_name='신청 받은 사람의 결정 시간')),
                ('receiver_decision', models.BooleanField(verbose_name='친구 신청 수락 여부')),
                ('sender_decision', models.BooleanField(verbose_name='친구 신청 여부')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_decisions', to=settings.AUTH_USER_MODEL, verbose_name='받은 사람')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_decisions', to=settings.AUTH_USER_MODEL, verbose_name='보낸 사람')),
            ],
        ),
    ]
