# Generated by Django 4.0.2 on 2022-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_degree_userprofile_dormitory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=16)),
                ('name_en', models.CharField(default='', max_length=64)),
                ('name_ko', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
