# Generated by Django 4.0.2 on 2022-03-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='', max_length=64)),
                ('name_ko', models.CharField(default='', max_length=64)),
                ('abbreviation_ko', models.CharField(default='', max_length=64)),
                ('acronym_en', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
