# Generated by Django 4.0.2 on 2022-03-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_en', models.CharField(default='', max_length=64)),
                ('degree_ko', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
