# Generated by Django 4.0.2 on 2022-03-27 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, verbose_name='카테고리')),
                ('text', models.CharField(max_length=64, verbose_name='카테고리 텍스트')),
            ],
        ),
        migrations.CreateModel(
            name='FriendPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.needs', verbose_name='사용자 니즈')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
