# Generated by Django 4.0.2 on 2022-04-01 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_needs_friendpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.major', verbose_name='전공'),
        ),
    ]
