# Generated by Django 4.0.2 on 2022-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_receiver_id_frienddecision_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='girl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='undergraduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='boy',
            field=models.BooleanField(default=False),
        ),
    ]
