# Generated by Django 4.0.2 on 2022-03-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dormitory_girl_dormitory_graduate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frienddecision',
            name='receiver_decision',
            field=models.BooleanField(default=False, verbose_name='친구 신청 수락 여부'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frienddecision',
            name='sender_decision',
            field=models.BooleanField(default=False, verbose_name='친구 신청 여부'),
            preserve_default=False,
        ),
    ]
