from .user_profile import UserProfile
from .profile_image import ProfileImage
from .degree import Degree
from .dormitory import Dormitory
from .friend_decision import FriendDecision
from .course import Course
from .major import Major
from .needs import Needs
from .friend_preference import FriendPreference
